#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# home:
#   path: /
#   controller: App\Controller\HomeController::index
# proprety.index:
#   path: /biens
#   controller: App\Controller\PropretyController::index
